# -*- coding: utf-8 -*-
"""mentor task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OajUKz_w8qbuA3oCKsTi9DN1KjH8CQvB
"""

from pymongo import MongoClient
gokul=MongoClient("mongodb://gokul:abcdefgh@ac-dfc1yni-shard-00-00.fj9tqo4.mongodb.net:27017,ac-dfc1yni-shard-00-01.fj9tqo4.mongodb.net:27017,ac-dfc1yni-shard-00-02.fj9tqo4.mongodb.net:27017/?ssl=true&replicaSet=atlas-g7k5lh-shard-0&authSource=admin&retryWrites=true&w=majority")

g1=gokul["sample_mflix"]

b1=g1["movies"]

for i in b1.find({"$and":[{"year":{"$gt":1950,"$lt":1970}},{"genres":{"$in":["Comedy","Horror","Fantasy"]}},{"$or":[{"tomatoes.viewer.rating":{"$gt":3}},{"imdb.rating":{"$gt":7}},{"awards.wins":{"gte":1}}]}]},{"_id":0,"title":1,"directors":1,"music dirctors":1,"cast":1,"imdb.rating":1,"tomatoes.viewer.rating":1}):
  print(i)
for i in b1.find({"$and":[{"year":{"$gt":2000,"$lt":2015}},{"genres":{"$in":["Comedy","Horror","Fantasy"]}},{"$or":[{"tomatoes.viewer.rating":{"$gt":3}},{"imdb.rating":{"$gt":7}},{"awards.wins":{"gte":1}}]}]},{"_id":0,"title":1,"directors":1,"music dirctors":1,"cast":1,"imdb.rating":1,"tomatoes.viewer.rating":1}):
  print(i)

l1=[]
for i in b1.find({"$and":[{"year":{"$gt":1950,"$lt":1970}},{"genres":{"$in":["Comedy","Horror","Fantasy"]}},{"$or":[{"tomatoes.viewer.rating":{"$gt":3}},{"imdb.rating":{"$gt":7}},{"awards.wins":{"gte":1}}]}]},{"_id":0,"title":1,"directors":1,"music dirctors":1,"cast":1,"imdb.rating":1,"tomatoes.viewer.rating":1}):
  l1.append(i)
for i in b1.find({"$and":[{"year":{"$gt":2000,"$lt":2015}},{"genres":{"$in":["Comedy","Horror","Fantasy"]}},{"$or":[{"tomatoes.viewer.rating":{"$gt":3}},{"imdb.rating":{"$gt":7}},{"awards.wins":{"gte":1}}]}]},{"_id":0,"title":1,"directors":1,"music dirctors":1,"cast":1,"imdb.rating":1,"tomatoes.viewer.rating":1}):
  l1.append(i)

import pandas as pd

df=pd.DataFrame(l1)
df